---
# Apache2 tasks for rails_app

- name: Copy helper macro configuration file.
  copy:
    src: files/rails.conf
    dest: "{{ apache2_config_enabled_path }}/rails_app_macro.conf"
    mode: 0644

- name: Install required Apache2 modules
  apache2_module:
    name: "{{ item }}"
  loop: "{{ apache2_modules }}"
  notify: restart apache2
