---
# Ligttpd tasks for rails_app

- name: Install lighttpd specific packages
  package: name={{ packages }}
  vars:
    packages: "{{ rails_app_lighttpd }}"

- name: Copy helper lua script
  copy:
    src: files/rails.lua
    dest: "{{ lighttpd_config_path }}/rails.lua"
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_group }}"
    mode: 0644
