---
# Ligttpd tasks for rails_app

- name: Install lighttpd specific packages
  package: name={{packages}}
  vars:
    packages:
      - lighttpd-mod-magnet
      - lua5.3

- name: Copy helper lua script.
  copy:
    src: ../files/rails.lua
    dest: "{{lighttpd_config_dir}}/rails.lua"
    owner: "{{lighttpd_user}}"
    group: "{{lighttpd_group}}"
