---
# postgresql tasks file for rails_app

- name: Install database package dependencies
  package:
    name: "{{ item }}"
  loop: "{{ rails_app_postgresql }}"

- name: Create application database user
  postgresql_user:
    name: "{{ rails_app_db.username }}"
    password: "{{ rails_app_db.password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  become: true
  become_user: postgres

- name: Create application databases
  postgresql_db:
    name: "{{ rails_app_db.database }}"
    owner: "{{ rails_app_db.username }}"
  become: true
  become_user: postgres
