---
- name: Converge
  hosts: all

  vars_files:
    - rails_app.yml
    - goss.yml

  vars:
    db_to_gem:
      postgresql: >-
        'pg', '>= 0.18', '< 2.0'
      mysql2: >-
        'mysql2', '>= 0.4.4', '< 0.6.0'

    rails_app_proxy: "{{lookup('env', 'RAILS_APP_PROXY')}}"

  roles:
    - role: rails_app

  environment:
    RAILS_ENV: "production"

  tasks:
    - name: Add support for connecting to database
      copy:
        dest: "{{rails_app_path}}/Gemfile.local"
        content: "gem {{db_to_gem[rails_app_db_adapter] | mandatory}}"
      become: true
      become_user: "{{rails_app_user}}"

    - name: Install required gems
      command: bundle install --without development test --path={{rubygems_path}}
      args:
        chdir: "{{rails_app_path}}"
        creates: "{{rails_app_path}}/Gemfile.lock"
      environment:
        PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
      become: true
      become_user: "{{rails_app_user}}"

    - name: Run database migrations
      command: rake db:migrate
      args:
        chdir: "{{rails_app_path}}"
      environment:
        PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
      become: true
      become_user: "{{rails_app_user}}"
      changed_when: false

    - name: Create tasks for testing
      command: rake db:seed
      args:
        chdir: "{{rails_app_path}}"
      environment:
        PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
      become: true
      become_user: "{{rails_app_user}}"
      changed_when: false

    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{goss_test_variables}}
      notify: restart rails_app
