---
- name: Converge
  hosts: all

  vars_files:
    - rails_app.yml
    - goss.yml

  vars:
    db_to_gem:
      postgresql: >-
        'pg', '>= 0.18', '< 2.0'
      mysql2: >-
        'mysql2', '>= 0.4.4', '< 0.6.0'

    rails_app_proxy: "{{ lookup('env', 'RAILS_APP_PROXY') }}"

  roles:
    - role: rails_app

  environment:
    RAILS_ENV: "production"

  tasks:

    - name: Create tasks for testing
      command: rake db:seed
      args:
        chdir: "{{ rails_app_path }}"
      environment:
        PATH: "{{ rubygems_path }}/bin:{{ ansible_env.PATH }}"
      become: true
      become_user: "{{ rails_app_user }}"
      changed_when: false

    - name: Create file for testing
      copy:
        dest: "{{ rails_app_files_path }}/hello.txt"
        content: |
          Hello World !!!
        mode: 0644
        owner: "{{ rails_app_user }}"
        group: "{{ rails_app_proxy_group }}"

    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{ goss_test_variables }} mode=0644

    - name: Restart services
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - "{{ rails_app_name }}"
        - "{{ rails_app_proxy }}"
      changed_when: false
