---
- name: Prepare
  hosts: all

  vars_files:
    - rails_app.yml

  vars:
    adapter_role:
      mysql2: mariadb

    mariadb_root_password: >-
      {{lookup('password', '/tmp/mariadb_password chars=ascii_letters,digits,hexdigits')}}

  pre_tasks:
    - name: Setup image for keeping downloaded packages
      file:
        path: /etc/apt/apt.conf.d/docker-clean
        state: absent
      when: ansible_os_family == 'Debian'

  roles:
    - "{{adapter_role[rails_app_db_adapter] | default(rails_app_db_adapter)}}"

  tasks:

    - name: Install dependencies
      package: name=git

    - name: Download rails application code
      git:
        repo: https://github.com/bithium/rails_app_todo.git
        dest: "{{rails_app_path}}"
        force: true
        depth: 1

    - name: Fix checkout folder permission's
      file:
        path: "{{rails_app_path}}"
        mode: "o+w"
        recurse: true

    - name: Tweak hosts file for application testing
      lineinfile:
        path: "/etc/hosts"
        line: "127.0.0.1  {{rails_app_fqdn}}"
        unsafe_writes: true
