---
rails_app_name: "todo"
rails_app_user: "sandbox"

rails_app_db_adapter: "{{ lookup('env', 'RAILS_APP_DB') }}"

rails_app_db:
  database: "{{ rails_app_name }}"
  username: "{{ rails_app_user }}"
  password: >-
    {{ lookup('password', '/tmp/rails_app_password chars=ascii_letters,digits,hexdigits') }}

rails_app_fqdn: "todo.example.com"

rails_app_path: "/var/www/{{ rails_app_name }}"
