---
rails_app_name: "todo"
rails_app_user: "sandbox"

rails_app_db_adapter: "{{ lookup('env', 'RAILS_APP_DB') }}"

rails_app_db:
  database: "{{ rails_app_name }}"
  username: "{{ rails_app_user }}"
  password: >-
    {{ lookup('password', '/tmp/rails_app_password chars=ascii_letters,digits,hexdigits') }}

rails_app_fqdn: "todo.example.com"

rails_app_repo_url: "/var/cache/repos/{{ rails_app_name }}"
rails_app_version: "v0.2.1"

rails_app_gems_cache_proxy: "{{ lookup('env', 'RAILS_APP_GEM_CACHE_PROXY') | default(omit) }}"
