---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: rails_app-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
      - "/mnt/mirrors/repos:/var/cache/repos"
    command: /sbin/init
provisioner:
  name: ansible
  # log: true
  config_options:
    defaults:
      interpreter_python: "/usr/bin/python3"
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
    verify: ../common/verify.yml
  env:
    RAILS_APP_DB: postgresql
    RAILS_APP_PROXY: apache2
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
scenario:
  name: apache2
